[package]
name = "runas"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
runas-rs = { path = "../" }

[profile.release]
strip = true
codegen-units = 1
opt-level = "z"
lto = true